name: hrana
description: Dart client for hrana, a protocol for accessing libsql database servers.
version: 0.2.1
repository: https://github.com/simolus3/hrana.dart
topics:
  - database
  - turso
  - libsql
  - sqld
  - hrana

environment:
  sdk: ^3.4.0

dependencies:
  fixnum: ^1.1.0
  protobuf: ^3.1.0
  sqlite3: ^2.4.4
  stream_channel: ^2.1.2
  web_socket_channel: ^3.0.0
  # path: ^1.8.0

dev_dependencies:
  docker_process: ^1.3.1
  lints: ^3.0.0
  logging: ^1.2.0
  test: ^1.24.0
