name: drift_hrana
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  drift: ^2.18.0
  hrana: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.18.0
  lints: ^3.0.0
  test: ^1.24.0
